name: Greetings

on: 
  pull_request_target: 
    types: [opened]
  issues: 
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Greet New Contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 **Welcome to the repository!**  
            Thank you for opening an issue. We appreciate your feedback and will respond as soon as possible.  
            Feel free to provide more details if necessary.  
          pr-message: |
            🎉 **Thank you for your contribution!**  
            We appreciate you opening this pull request. Our maintainers will review it shortly.  
            Feel free to update your PR if you have any changes in mind.  
